home/urls.py
from django.urls import path, include


from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

posts/urls.py
from django.urls import path, include


from . import views

app_name = 'posts'

urlpatterns = [
    path('<int:obj_id>/post/search', views.post_search, name='post-search'),
    path('<int:obj_id>/comments/search', views.comment_search, name='comment-search'),
    path('<int:obj_id>/comments/', views.comment_likes, name='comments'),
    path('<int:post_id>/likes/', views.post_likes, name='likes'),
    path('<int:post_id>/', views.post, name='post'),
]

project_ig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import sign_up, login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('post/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('home.urls')),
    path('register/', views.sign_up, name='sign_up'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('search/', views.search, name='search'),
    path('<str:username>/following/search/', views.following_search, name='following_search'),
    path('<str:username>/followers/search/', views.followers_search, name='followers_search'),
    path('<str:username>/following/', views.following, name='following'),
    path('<str:username>/followers/', views.followers, name='followers'),
    path('<str:username>/', views.profile, name='profile'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from posts.models import PostModel
from users.models import CustomUser

from helpers.posts import get_total_likes, check_user_like

# Create your views here.


@login_required
def home(request):
    if request.method == 'POST':
        return HttpResponse('Sorry. :(') # TODO: Implementar post
    logged_user = get_object_or_404(CustomUser, username=request.user)
    following_users = logged_user.following.all()
    posts = PostModel.objects.filter(user__in=following_users)
    return render(request, "home/index.html", {"posts":posts, "logged_user":logged_user})

templates/home/index.html
{% extends "base.html" %}
{% load custom_tags %}

{%block content %}
    <main>
        <div class="main">
                {% for post in posts %}
                    <div class="post">
                        <a href="{% url 'users:profile' username=post.user.username %}">
                            <div class="post-header">
                                <div class="user-icon round-icon pointer-on-hover">
                                    <img src="{{ MEDIA_URL }}{{ post.user.profile_picture }}" alt="Foto de perfil do usuário do post" height="24" width="24">
                                </div>
                                <p class="pointer-on-hover">{{ post.user.username }}</p>
                            </div>
                        </a>
                        <div class="post-img">
                            <!-- TODO: Gerar alt dinâmicamente? -->
                            <img src="{{ MEDIA_URL }}{{ post.img }}" alt="Imagem top">
                        </div>
                        <div class="post-info">
                            <div class="post-interactions">
                                <div class="post-like-button pointer-on-hover">
                                    <input type="hidden" value="{% if post|check_user_like:logged_user.username %}liked{% else %}not-liked{% endif %}" class="like-status">
                                    <input type="hidden" value="{{ post.id }}" class="obj-id">
                                    <input type="hidden" value="post" class="type">
                                    <svg aria-label="Curtir" class="not-liked {% if post|check_user_like:logged_user.username %}hide-icon{% endif %}" fill="currentColor" height="24" role="img" viewBox="0 0 24 24" width="24">
                                        <title>Curtir</title>
                                        <path d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938m0-2a6.04 6.04 0 0 0-4.797 2.127 6.052 6.052 0 0 0-4.787-2.127A6.985 6.985 0 0 0 .5 9.122c0 3.61 2.55 5.827 5.015 7.97.283.246.569.494.853.747l1.027.918a44.998 44.998 0 0 0 3.518 3.018 2 2 0 0 0 2.174 0 45.263 45.263 0 0 0 3.626-3.115l.922-.824c.293-.26.59-.519.885-.774 2.334-2.025 4.98-4.32 4.98-7.94a6.985 6.985 0 0 0-6.708-7.218Z"></path>
                                    </svg>
                                    <span class="{% if not post|check_user_like:logged_user.username %}hide-icon{% endif %}">
                                        <svg aria-label="Descurtir" fill="currentColor" height="24" role="img" viewBox="0 0 48 48" width="24">
                                            <title>Descurtir</title>
                                            <path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path>
                                        </svg>
                                    </span>
                                </div>
                                <div class="post-comment pointer-on-hover">
                                    <svg aria-label="Comentar" fill="currentColor" height="24" role="img" viewBox="0 0 24 24" width="24">
                                        <title>Comentar</title>
                                        <path d="M20.656 17.008a9.993 9.993 0 1 0-3.59 3.615L22 22Z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path>
                                    </svg>
                                </div>
                            </div>
                            <div class="info-data pointer-on-hover">
                                <p class="likes-qty">{{ post|get_total_likes }}</p><p>curtida(s)</p>
                            </div>
                            <div class="post-description">
                                {{ post.description|linebreaks }}
                                <div class="more-button">
                                    <p class="pointer-on-hover">... mais</p>
                                </div>
                            </div>
                        </div>
                        <div class="post-comments">
                            <div class="show-comments pointer-on-hover">
                                <input type="hidden" value="{% url 'posts:post' post_id=post.id %}" class="post-url">
                                {% if post|get_total_comments > 1 %}
                                <p>Ver todos os {{ post|get_total_comments }} comentários</p>
                                {% elif post|get_total_comments == 1 %}
                                <p>Ver comentário</p>
                                {% else %}
                                <p>Sem comentários</p>
                                {% endif %}
                            </div>
                            <div class="input-comment dm-sans-primary-font-light">
                                <textarea name="comment" placeholder="Adicione um comentário"></textarea>
                                <div class="hide-icon">
                                    <p class="pointer-on-hover">Publicar</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </div>
    </main>
            


{%endblock%}