home/urls.py
from django.urls import path, include


from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

posts/urls.py
from django.urls import path, include


from . import views

app_name = 'posts'

urlpatterns = [
    path('<int:obj_id>/post/search', views.post_search, name='post-search'),
    path('<int:obj_id>/comments/search', views.comment_search, name='comment-search'),
    path('<int:obj_id>/comments/', views.comment_likes, name='comments'),
    path('<int:post_id>/likes/', views.post_likes, name='likes'),
    path('<int:post_id>/', views.post, name='post'),
]

project_ig/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import sign_up, login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('post/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('home.urls')),
    path('register/', views.sign_up, name='sign_up'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('search/', views.search, name='search'),
    path('<str:username>/following/search/', views.following_search, name='following_search'),
    path('<str:username>/followers/search/', views.followers_search, name='followers_search'),
    path('<str:username>/following/', views.following, name='following'),
    path('<str:username>/followers/', views.followers, name='followers'),
    path('<str:username>/', views.profile, name='profile'),
]

users/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):


    email = models.EmailField(unique=True, name='email')
    bio = models.TextField(max_length=600, default='', blank=True, name='bio')
    following = models.ManyToManyField(to='self', blank=True, symmetrical=False, default=None, related_name='followers')
    profile_picture = models.ImageField(upload_to='images/profiles/%Y/%d', default='images/profiles/default/default-user-icon.jpg')


    def __str__(self):
        return self.username
    

    def is_following(self, user_id):
        if self.following.filter(id=user_id).exists():
            return True
        else:
            return False
        

    def save(self, *args, **kwargs):
        super(CustomUser, self).save(*args, **kwargs)
        image = Image.open(self.profile_picture.path)
        image.save(self.profile_picture.path, 'JPEG', quality=40,optimize=True)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms


from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(label='email')  

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

users/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse, HttpRequest, HttpResponse, HttpResponseRedirect

from .forms import CustomUserCreationForm, LoginForm
from .models import CustomUser
from posts.models import PostModel, CommentModel

from helpers.users import follow_or_unfollow_user, remove_follower, get_total_following, get_total_followers, search_user, FOLLOWERS, FOLLOWING


def sign_up(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.user.is_authenticated:
        return redirect(reverse('users:profile', kwargs={'username': request.user.username}))
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'users/register.html', {'form': form})


def login_view(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.user.is_authenticated:
        return redirect(reverse('users:profile', kwargs={'username': request.user}))
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'Welcome back.')
                return redirect(reverse('users:profile', kwargs={'username': username}))
            else:
                messages.error(request, 'Invalid username or password')
                return render(request, 'users/login.html',{'form': form})
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})


@login_required
def logout_view(request: HttpRequest) -> HttpResponseRedirect:
    logout(request)
    return redirect('users:login')


@login_required
def profile(request: HttpRequest, username: str) -> HttpResponse | JsonResponse:
    page_user = get_object_or_404(CustomUser, username=username)
    logged_user = request.user
    if request.method == 'POST':
        data = json.loads(request.body)
        if 'action' not in data.keys():
            raise ValueError("Missing 'action' tag in POST request.")
        
        if data['action'] == 'follow-unfollow':
            return follow_or_unfollow_user(data, logged_user, page_user)
        elif data['action'] == 'remove-follower':
            return remove_follower(data, logged_user, page_user)
        else:
            ValueError(f"Invalid 'action' key, expected 'remove-follower' or 'follow-unfollow', but {data['action']} was passed.")
    

    posts = page_user.posts.all().values()
    for post_dict in posts:
        post_obj = PostModel.objects.get(id=post_dict['id'])
        post_dict.update(
            {
                'likes': post_obj.likes.all().count(),
                'comments': CommentModel.objects.filter(post=post_obj).count(),
            })
    return render(request, 'users/profile.html',
                   {
                        'profile_user': page_user,
                        'posts': posts,
                        'logged_user': logged_user,
                        'is_following': logged_user.is_following(page_user.id),
                        'following_qty': get_total_following(page_user),
                        'followers_qty': get_total_followers(page_user),
                    })
    

@login_required
def following(request: HttpRequest, username: str) -> HttpResponse:
    if request.method == 'GET': 
        page_user =  get_object_or_404(CustomUser, username=username)
        logged_user = get_object_or_404(CustomUser, username=request.user)
        following_list = [(user, logged_user.is_following(user.id)) for user in page_user.following.all()]
        return render(request, 'users/users_card.html',
                        {
                            'profile_user': page_user,
                            'user_list': following_list,
                            'logged_user': logged_user,
                            'page_title': 'Seguindo',
                            'search_url': reverse('users:following_search', kwargs={'username':username}),
                        })
    else:
        return HttpResponseBadRequest('Only GET requests are allowed.')

@login_required
def followers(request: HttpRequest, username: str) -> HttpResponse:
    if request.method == 'GET': 
        page_user =  get_object_or_404(CustomUser, username=username)
        logged_user = get_object_or_404(CustomUser, username=request.user)
        followers_list = [(user, logged_user.is_following(user.id))
                        for user in CustomUser.objects.filter(following=page_user)]
        return render(request, 'users/users_card.html',
                        {
                            'profile_user': page_user,
                            'user_list': followers_list,
                            'logged_user': logged_user,
                            'page_title': 'Seguidores',
                            'search_url': reverse('users:followers_search', kwargs={'username':username}),
                        })
    else:
        return HttpResponseBadRequest('Only GET requests are allowed.')

@login_required
def search(request: HttpRequest) -> JsonResponse:
    if request.method == 'GET':
        query = request.GET.get('q', '')
        t = search_user(substring=query, logged_user=request.user)
        return JsonResponse({
            'user_list': search_user(substring=query, logged_user=request.user),
            'profile_user': None,
            'show_bio': False,
            'show_relationship': False,
            'show_remove': False,
        }) 
    else:
        return HttpResponseBadRequest('Only GET requests are allowed.')


@login_required
def following_search(request: HttpRequest, username: str) -> JsonResponse:
    if request.method == 'GET':
        query = request.GET.get('q', '')
        return JsonResponse({
            'user_list': search_user(substring=query, logged_user=request.user, search_in=FOLLOWING, identification=username),
            'profile_user': username,
            'show_bio': True,
            'show_relationship': True,
            'show_remove': False,
        })
    else:
        return HttpResponseBadRequest('Only GET requests are allowed.')
    

@login_required
def followers_search(request: HttpRequest, username: str) -> JsonResponse:
    if request.method == 'GET':
        query = request.GET.get('q', '')
        return JsonResponse({
            'user_list': search_user(substring=query, logged_user=request.user, search_in=FOLLOWERS, identification=username),
            'profile_user': username,
            'show_bio': True,
            'show_relationship': True,
            'show_remove': (username == request.user.username),
        })
    else:
        return HttpResponseBadRequest('Only GET requests are allowed.')
    

templates/users/following-followers.html
<div class="background-cover">
    <div class="relationship-view-card">
        <div class="relationship-card-header">
            <div class="card-title">
                <h2 class="title">{{ page_title }}</h2>
            </div>
            <div class="overlay-close-button pointer-on-hover">&#x2715</div>
            <div class="search white-border-top">
                <input type="text" name="search" placeholder="Search user">
            </div>
        </div>
        <div class="users">
            {% if user_list %}
            <ul class="users-list">
                {% for user, is_following in user_list %}
                <li class="user-item">
                    <div class="user-info">
                        <div class="user-icon round-icon">
                            <img src="{{ MEDIA_URL }}{{ user.profile_picture }}" alt="" width="50" height="50">
                        </div>
                        <span>
                            <a href="{% url 'users:profile' username=user.username %}">
                                <p>{{ user.username }}</p>
                            </a>
                            {% if profile_user.bio %}
                            <p class="max-text">{{ user.bio }}</p>
                            {% endif %}
                        </span>
                    </div>
                    <div class="relationship-buttons">
                        <input type="hidden" class="username" value="{{ user.username }}">
                        {% if profile_user == logged_user and page_title == 'Seguidores' %}
                        <div class="profile-button remove-follower pointer-on-hover">
                            Remover
                        </div>
                        {% endif %}
                        {% if user != logged_user %}
                        <div class="profile-button follow-button pointer-on-hover {% if is_following %}unfollow-button{% endif %}">
                            {% if is_following %}
                            Seguindo
                            {% else %}
                            Seguir
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>Vazio</p>
            {% endif %}
        </div>
    </div>
</div>

templates/users/following.html
{% extends 'base.html' %}

{% block title %} Following {% endblock %}
{% block content %}
    <div>
        <div>
            <img src="{{ MEDIA_URL }}{{ profile_user.profile_picture }}" alt="" width="100" height="100">
        </div>
        <h1>
            {{ profile_user.username }}
        </h1>
    </div>
    {% if following_list %}
        {% for user, is_following in following_list %}
            <div>
                <div>
                    <img src="{{ MEDIA_URL }}{{ user.profile_picture }}" alt="" width="100" height="100">
                </div>
                <input type="hidden" class="username" value="{{ user.username }}">
                <button type="button" class="follow-button">
                    {% if is_following %}
                        Unfollow
                    {% else %}
                        Follow
                    {% endif %}
                </button>
                <p>{{ user.username }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>You are not following anyone</p>
    {% endif %}

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}


{% block title %} Profile {% endblock %}
{% block content %}
    <div class="profile-main">
        <header>
            <div class="profile-header">
                <div class="profile-picture-div">
                    <img class="profile-picture-img" src="{{ MEDIA_URL }}{{ profile_user.profile_picture }}" alt="Profile picture">
                </div>
                <div>

                    <div class="profile-options">
                        <div>
                            <h2 class="profile-username">
                                {{ profile_user.username }}
                            </h2>
                        </div>
                        {% if logged_user.username != profile_user.username %}
                        <div class="profile-header-buttons">
                            <input type="hidden" class="post-url" value="{{ request.get_full_path }}">
                            <input type="hidden" class="username" value="{{ profile_user.username }}">
                            {% if is_following %}
                                <p class="profile-button follow-button unfollow-button">
                                    Seguindo
                                </p>
                            {% else %}
                                <p class="profile-button follow-button">
                                    Seguir
                                </p>
                            {% endif %}
                        </div>
                        {% else %}
                        <div class="profile-header-buttons">
                            <a class="profile-button" href="">Configurações</a>
                            <a class="profile-button" href="">Arquivo</a>
                        </div>
                        {% endif %}
                    </div>
                    <div class="profile-spacer"></div>
                    <div>
                        <ul class="profile-info">
                            <li>{{ posts|length }} publicações</li>
                            <li class="relationship-button pointer-on-hover">
                                <input type="hidden" value="{% url 'users:followers' username=profile_user.username %}" class="followers-url">
                                <p>{{ followers_qty }} seguidores</p>
                            </li>
                            <li class="relationship-button pointer-on-hover">
                                <input type="hidden" value="{% url 'users:following' username=profile_user.username %}" class="following-url">
                                <p>{{ following_qty }} seguindo</p>
                            </li>
                        </ul>  
                    </div>
                    <div class="profile-bio">
                        {% if profile_user.bio %}
                        <p>
                        {{ profile_user.bio }}
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
        <main>
            <div>
                {% if posts %}
                <div class="post-grid-div">
                    {% for post in posts %}
                    <a href="{% url 'posts:post' post_id=post.id %}" class="post-div">
                        <div>
                            <!-- TODO: Alt da imagem do post -->
                            <img src="{{ MEDIA_URL }}{{ post.img }}" alt="">
                        </div>
                        <div class="post-overlay">
                            <div class="post-info-overlay">
                                <svg aria-label="Descurtir" fill="currentColor" height="16" role="img" viewBox="0 0 48 48" width="16">
                                    <title>Descurtir</title>
                                    <path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path>
                                </svg>
                                <p>{{ post.likes }}</p>
                            </div>
                            <div class="post-info-overlay">
                                <svg aria-label="Comentar" class="x1lliihq x1n2onr6 x5n08af" fill="currentColor" height="16" role="img" viewBox="0 0 24 24" width="16">
                                    <title>Comentar</title>
                                    <path d="M20.656 17.008a9.993 9.993 0 1 0-3.59 3.615L22 22Z" fill="currentColor" stroke="currentColor" stroke-linejoin="round" stroke-width="2"></path>
                                </svg>
                                <p>{{ post.comments }}</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
                {% else %}
                <div>
                    <p>Sem postagens</p>
                </div>
                {% endif %}
            </div>
        </main>
    </div>
    
    {% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

templates/users/users_card.html
<div class="background-cover">
    <div class="relationship-view-card">
        <div class="relationship-card-header">
            <div class="card-title">
                <h2 class="title">{{ page_title }}</h2>
            </div>
            <div class="overlay-close-button pointer-on-hover">&#x2715</div>
            <div class="search white-border-top">
                <input type="hidden" value="{{ search_url }}" class="search-url">
                <input type="text" name="search" placeholder="Search user" class="search-input">
            </div>
        </div>
        <div class="users">
            {% if user_list %}
            <ul class="users-list">
                {% for user, is_following in user_list %}
                <li class="user-item">
                    <div class="user-info">
                        <div class="user-icon round-icon">
                            <img src="{{ MEDIA_URL }}{{ user.profile_picture }}" alt="" width="50" height="50">
                        </div>
                        <span>
                            <a href="{% url 'users:profile' username=user.username %}">
                                <p>{{ user.username }}</p>
                            </a>
                            {% if user.bio %}
                            <p class="max-text">{{ user.bio }}</p>
                            {% endif %}
                        </span>
                    </div>
                    <div class="relationship-buttons">
                        <input type="hidden" class="post-url" value="{% if profile_user %} {% url 'users:profile' username=profile_user.username %} {% else %} {% url 'users:profile' username=user.username %} {% endif %}">
                        <input type="hidden" class="username" value="{{ user.username }}">
                        {% if profile_user == logged_user and page_title == 'Seguidores' %}
                        <div class="profile-button remove-follower pointer-on-hover">
                            Remover
                        </div>
                        {% endif %}
                        {% if user != logged_user %}
                        <div class="profile-button follow-button pointer-on-hover {% if is_following %}unfollow-button{% endif %}">
                            {% if is_following %}
                            Seguindo
                            {% else %}
                            Seguir
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="center-text">
                <p>Vazio</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>